# CSHRC

alias .. 'cd ../'
alias g 'git'
alias gwc 'git whatchanged -p --abbrev-commit --pretty=medium'
alias glg="git log --pretty=format:'%C(yellow)%h %C(cyan)%ad%Cgreen%d %Creset%s' --date=short"
alias vi 'vim'
alias ls 'ls -h --color=always'
alias ll 'ls -o'

setenv EDITOR 'vim'

# set path = ($path /home/hoover/u7/jwarn10/GitHub/util)
